/* +++Date last modified: 05-Jul-1997 */

/*
**        A Pratt-Boyer-Moore string search, written by Jerry Coffin
**  sometime or other in 1991.  Removed from original program, and
**  (incorrectly) rewritten for separate, generic use in early 1992.
**  Corrected with help from Thad Smith, late March and early
**  April 1992...hopefully it's correct this time. Revised by Bob Stout.
**
**  This is hereby placed in the Public Domain by its author.
**
**  10/21/93 rdg  Fixed bug found by Jeff Dunlop
*/

#include <stddef.h>
#include <string.h>
#include <limits.h>

static size_t table[UCHAR_MAX + 1];
static size_t len;
static char *findme;

#define ITERS 330

/*
**  Call this with the string to locate to initialize the table
*/

void init_search(const char *string)
{
      size_t i;

      len = strlen(string);
      for (i = 0; i <= UCHAR_MAX; i++)                      /* rdg 10/93 */
            table[i] = len;
      for (i = 0; i < len; i++)
            table[(unsigned char)string[i]] = len - i - 1;
      findme = (char *)string;
}

/*
**  Call this with a buffer to search
*/

char *strsearch(const char *string)
{
      register size_t shift;
      register size_t pos = len - 1;
      char *here;
      size_t limit=strlen(string);

      while (pos < limit)
      {
            while( pos < limit &&
                  (shift = table[(unsigned char)string[pos]]) > 0)
            {
                  pos += shift;
            }
            if (0 == shift)
            {
                  if (0 == strncmp(findme,
                        here = (char *)&string[pos-len+1], len))
                  {
                        return(here);
                  }
                  else  pos++;
            }
      }
      return NULL;
}

#include <stdio.h>

main()
{
      char *here;
      char *find_strings[] = { "Kur",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"ipsum",
"Ipsum",
"Sed",
"sed",
"Nunc",
"nunc",
"Sit",
"sit",
"ipsum",
"Ipsum",
"Sed",
"sed",
"Nunc",
"nunc",
"Sit",
"sit",
"ipsum",
"Ipsum",
"Sed",
"sed",
"Nunc",
"nunc",
"Sit",
"sit",
"luctus",
"Ipsum",
"Sed",
"sed",
"Nunc",
"nunc",
"Sit",
"sit",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"diam",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"purus",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"pulvinar",
NULL};
      char *search_strings[] = { "Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Dont feel guilty if you dont know",
"what you want to do with your",
"life The most interesting people I",
"know didnt know at 22",
"what they wanted",
"to do with their lives Some of",
"the most interesting",
"40yearolds I know still dont",
"Get plenty of calcium",
"Be kind to your knees Youll miss",
"them when theyre gone",
"Maybe youll marry",
"maybe you wont Maybe youll have children maybe",
"you wont Maybe youll divorce at 40 maybe youll dance",
"the funky chicken on",
"your 75th wedding anniversary Whatever",
"you do dont congratulate yourself too",
"much or berate yourself",
"either Your choices are half chance So",
"are everybody elses",
"Enjoy your body Use",
"it every way you can Dont",
"be afraid of it or of what",
"other people think of",
"it Its",
"the",
"greatest instrument youll ever",
"own Dance even if you have",
"nowhere to do it but your living",
"room Read the directions even if",
"you dont follow them Do not read",
"beauty magazines They will only make you",
"feel ugly Get to know your parents You never",
"know when theyll be gone for good Be",
"nice to your siblings Theyre your",
"best link to your",
"past and the people most likely",
"to stick with you",
"in the future Understand that",
"friends come and go but",
"with a precious few you should hold",
"on Work hard to bridge",
"the gaps in geography and lifestyle",
"because the older",
"you get the more you need the",
"people who knew you when you",
"were young Live",
"in New York City once but leave before",
"it makes you hard Live in",
"Northern California once but leave",
"before it makes you soft Travel",
"Accept certain inalienable truths Prices will rise",
"Politicians will philander You too will",
"get old And when you do youll",
"fantasize that when you were young prices were",
"reasonable politicians were noble and children respected",
"their elders Respect your elders",
"Dont expect anyone else to",
"support you Maybe you have a",
"trust fund Maybe youll have a wealthy",
"spouse But you never know when either",
"one might run out Dont mess",
"too much with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
"Phasellus et mattis mi.",
"Vestibulum dictum ante metus, vitae convallis risus tempus eu.",
"Vestibulum ultricies eros et ligula laoreet aliquet.",
"Morbi porttitor tellus quam, vel pharetra ante consequat et.",
"Integer pharetra dui nisi.",
"Morbi dictum lacus sed dictum vulputate.",
"Vestibulum eu luctus ex.",
"Etiam mattis mauris sed accumsan posuere.",
"Donec purus nisl, imperdiet id justo eget, aliquam aliquet mi.",
"Curabitur euismod tincidunt felis, sed efficitur purus porttitor bibendum.",
"Nullam enim massa, ultrices a erat eget, laoreet dictum urna.",
"Quisque tempus justo id tempus mollis.",
"Etiam rutrum vitae erat vitae consectetur.",
"Etiam leo ante, volutpat vitae mauris non, pharetra scelerisque elit.",
"Vivamus id lobortis velit.",
"Mauris hendrerit, odio ac tempor pellentesque, lacus felis porta augue, sit amet ultricies orci risus a nisl.",
"Vestibulum non sapien maximus, commodo leo a, hendrerit erat.",
"Donec vitae viverra erat, sed dignissim purus.",
"Mauris pharetra nisl ligula, non semper nulla vulputate nec.",
"Maecenas accumsan, augue ac condimentum rhoncus, neque ante gravida nulla, ut gravida ante massa in velit.",
"Morbi et facilisis nisi.",
"Proin eu turpis et augue faucibus facilisis et nec velit.",
"Sed tristique est rutrum, scelerisque lorem quis, pharetra orci.",
"Aliquam volutpat laoreet massa in luctus.",
"Praesent suscipit arcu consectetur quam elementum mattis.",
"Pellentesque sed mattis nunc, et molestie turpis.",
"Vestibulum dui lorem, vulputate vitae facilisis et, consequat auctor turpis.",
"Donec eget tellus non erat gravida consectetur.",
"In lobortis velit nisi, a facilisis massa convallis eget.",
"Sed vestibulum nunc at ante dignissim euismod.",
"In ac laoreet felis.",
"Nulla feugiat finibus malesuada.",
"Integer sit amet massa sit amet elit tincidunt finibus.",
"Donec elementum ornare mi nec posuere.",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
"Proin suscipit convallis imperdiet.",
"Aliquam interdum in enim ac tristique.",
"Sed libero sapien, tempus eget fringilla in, lacinia id lacus.",
"Sed in est ac orci euismod viverra at vitae ipsum.",
"Ut viverra, dolor at interdum pulvinar, risus quam sagittis nisl, sit amet cursus felis ex nec mauris.",
"Quisque lobortis urna eget libero luctus tempor.",
"Maecenas ullamcorper est at lorem tincidunt, a imperdiet erat consectetur.",
"Nullam et sapien arcu.",
"Integer vestibulum tortor at libero rutrum consectetur.",
"Pellentesque quis aliquet elit.",
"Sed scelerisque lorem ut leo faucibus fringilla.",
"Duis finibus egestas pharetra.",
"Ut interdum nunc a ante feugiat, eu eleifend massa lobortis.",
"Maecenas molestie sapien ac elit blandit hendrerit.",
"Donec suscipit nibh ut enim ultrices, vel dictum neque cursus.",
"Vestibulum ut nisi vitae magna laoreet imperdiet.",
"Integer ut sollicitudin lorem.",
"Curabitur rutrum, sapien quis blandit molestie, ex sapien vulputate augue, non interdum lorem nulla vitae enim.",
"Fusce blandit vel massa id ornare.",
"In elit risus, blandit at mauris quis, tristique condimentum felis.",
"Nam convallis scelerisque leo, non congue lacus sagittis sed.",
"Proin et cursus augue.",
"Etiam ac magna mauris.",
"Cras pretium porta diam sit amet imperdiet.",
"Quisque blandit nunc sapien, sed rhoncus lorem tincidunt eget.",
"Vivamus pulvinar, orci sit amet hendrerit tempor, nisl turpis mattis sapien, id gravida magna mauris id risus.",
"Donec augue leo, rutrum nec dictum et, sagittis in sapien.",
"Nullam vel dapibus ex.",
"Morbi nec tortor ac libero vulputate commodo quis at quam.",
"Aenean ultrices mattis felis vel dapibus.",
"Curabitur ac tellus vitae ante vestibulum elementum sit amet a odio.",
"In hac habitasse platea dictumst.",
"Donec at vehicula arcu, sit amet sagittis nulla.",
"Nam sit amet accumsan purus.",
"In quis nulla dapibus, pulvinar eros eu, sodales urna.",
"Vestibulum sed eleifend metus.",
"Nam tortor tortor, vestibulum a quam at, commodo dapibus nisl.",
"Cras tempor eros non neque pharetra volutpat.",
"Sed nisi nisl, fringilla vitae arcu nec, imperdiet porta sapien.",
"Duis enim ante, egestas a nunc sit amet, laoreet sagittis ligula.",
"Donec ornare quis elit vel commodo.",
"Suspendisse potenti.",
"Nullam nisi urna, hendrerit ut laoreet id, placerat et metus.",
"Donec imperdiet hendrerit sem, sit amet placerat orci dignissim vel.",
"Nullam ultricies metus sapien, et venenatis ipsum vehicula non.",
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam erat volutpat.",
"Nulla fringilla scelerisque neque, nec cursus ligula aliquam eget.",
"Curabitur iaculis vestibulum metus, in dignissim lacus suscipit pellentesque.",
"Maecenas at nibh orci.",
"Nullam hendrerit felis ipsum, ut egestas elit maximus eu.",
"Aliquam erat volutpat.",
"Nulla vitae semper lacus.",
"Nulla convallis massa in aliquet commodo.",
"Integer pellentesque mattis purus, vel egestas leo congue ac.",
"Nulla facilisis ligula et justo mattis, gravida pellentesque risus aliquam.",
"Suspendisse potenti.",
"Duis sagittis mauris non accumsan tristique.",
"Suspendisse aliquam molestie massa et elementum.",
"Donec feugiat posuere orci, sit amet rutrum nibh viverra ultrices.",
"Quisque ac mauris in velit mollis dapibus id vitae diam.",
"Nullam et augue sapien.",
"In facilisis sollicitudin neque, ut mollis quam porta vel.",
"In feugiat ut augue non efficitur.",
"Nulla at hendrerit arcu, eu vehicula nibh.",
"Quisque nibh dolor, mollis non ex nec, sodales laoreet arcu.",
"Sed vulputate ligula vel massa euismod, in malesuada libero fringilla.",
"Mauris facilisis euismod nisi vel suscipit.",
"Sed auctor faucibus lorem, eget elementum purus porttitor interdum.",
"Morbi et ligula porta, tincidunt lorem quis, lobortis enim.",
"Phasellus vel rhoncus nisl.",
"Suspendisse efficitur tempor justo posuere porttitor.",
"Nulla eu ex aliquam, ultrices sapien et, imperdiet lorem.",
"Suspendisse eu malesuada diam.",
"Etiam a hendrerit orci, eu gravida metus.",
"Praesent laoreet, magna eu porta porttitor, est velit placerat ante, at dignissim lacus metus id risus.",
"Vestibulum a diam nec mauris dapibus rutrum.",
"Pellentesque nisi lectus, faucibus quis metus eu, gravida commodo nisi.",
"Cras ullamcorper dui interdum tellus cursus interdum in id erat.",
"Nunc in placerat nisl.",
"Vivamus eget euismod augue, ac euismod est.",
"Sed a lorem et ligula sagittis rhoncus at vel nunc.",
"Donec et maximus risus.",
"Maecenas quis nunc ante.",
"Nullam nisl massa, elementum vitae elit quis, maximus facilisis diam.",
"Phasellus at arcu ullamcorper, vulputate libero id, eleifend felis.",
"Nam faucibus aliquet orci nec sodales.",
"Donec fermentum commodo feugiat.",
"Morbi pharetra a mauris ac porttitor.",
"Nam rutrum, nibh in malesuada interdum, lacus augue tempus dui, id sagittis urna urna sed nisi.",
"Morbi volutpat faucibus mi, id finibus massa tempor a.",
"Aenean vitae aliquet ante, at rhoncus risus.",
"Praesent et fringilla nisl, vitae venenatis sapien.",
"Donec nec pellentesque magna.",
"Duis suscipit lacus vehicula nibh cursus aliquam.",
"Mauris volutpat ante nec tortor vehicula interdum.",
"Integer vel justo vulputate, iaculis dui eget, dictum urna.",
"Sed auctor libero quis turpis pulvinar semper vel quis dui.",
"Praesent vitae vehicula odio.",
"Praesent non orci a lorem dictum consequat eget ac ante.",
"In fringilla mollis augue.",
"Nulla facilisi.",
"Suspendisse dui mi, congue a efficitur ac, auctor maximus ipsum.",
"Nunc placerat iaculis egestas.",
"Nunc pretium leo id nunc pulvinar, ac pellentesque odio vestibulum.",
"Phasellus varius nibh nec nisi convallis, et venenatis lorem molestie.",
"Sed iaculis sem id est suscipit, nec eleifend urna cursus.",
"Mauris tempus cursus orci, at facilisis est tincidunt eget.",
"Praesent nisl ante, semper quis lacinia vulputate, bibendum nec lectus.",
"Morbi elementum consequat hendrerit.",
"In non sollicitudin elit, nec aliquam urna.",
"Etiam euismod libero ut nulla tincidunt eleifend.",
"Sed quis faucibus eros.",
"Mauris sit amet dui a velit tempor volutpat non ac purus.",
"Etiam cursus ante a malesuada consectetur.",
"Proin ultrices commodo ullamcorper.",
"Praesent auctor risus dui, et convallis augue semper quis.",
"In nec faucibus tellus, ultricies blandit enim.",
"Nulla facilisi.",
"Nullam id scelerisque lacus.",
"Sed laoreet tellus nec bibendum tempus.",
"Vestibulum in dolor blandit, tempor arcu ut, tristique ante.",
"Maecenas pulvinar ex id elit molestie viverra.",
"Cras viverra viverra justo eget feugiat.",
"Praesent efficitur, massa ac viverra malesuada, ex ligula malesuada ante, sit amet elementum lacus felis non mauris.",
"Proin at diam placerat quam tincidunt convallis.",
"Morbi venenatis metus nisi, sed facilisis libero ultrices vitae.",
"Phasellus non sem eget lectus ultrices tempus vitae nec sapien.",
"Morbi maximus viverra est, a lobortis justo ornare vitae.",
"Nunc non pretium ex, vitae porta elit.",
"Suspendisse efficitur magna risus.",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
"Phasellus et mattis mi.",
"Vestibulum dictum ante metus, vitae convallis risus tempus eu.",
"Vestibulum ultricies eros et ligula laoreet aliquet.",
"Morbi porttitor tellus quam, vel pharetra ante consequat et.",
"Integer pharetra dui nisi.",
"Morbi dictum lacus sed dictum vulputate.",
"Vestibulum eu luctus ex.",
"Etiam mattis mauris sed accumsan posuere.",
"Donec purus nisl, imperdiet id justo eget, aliquam aliquet mi.",
"Curabitur euismod tincidunt felis, sed efficitur purus porttitor bibendum.",
"Nullam enim massa, ultrices a erat eget, laoreet dictum urna.",
"Quisque tempus justo id tempus mollis.",
"Etiam rutrum vitae erat vitae consectetur.",
"Etiam leo ante, volutpat vitae mauris non, pharetra scelerisque elit.",
"Vivamus id lobortis velit.",
"Mauris hendrerit, odio ac tempor pellentesque, lacus felis porta augue, sit amet ultricies orci risus a nisl.",
"Vestibulum non sapien maximus, commodo leo a, hendrerit erat.",
"Donec vitae viverra erat, sed dignissim purus.",
"Mauris pharetra nisl ligula, non semper nulla vulputate nec.",
"Maecenas accumsan, augue ac condimentum rhoncus, neque ante gravida nulla, ut gravida ante massa in velit.",
"Morbi et facilisis nisi.",
"Proin eu turpis et augue faucibus facilisis et nec velit.",
"Sed tristique est rutrum, scelerisque lorem quis, pharetra orci.",
"Aliquam volutpat laoreet massa in luctus.",
"Praesent suscipit arcu consectetur quam elementum mattis.",
"Pellentesque sed mattis nunc, et molestie turpis.",
"Vestibulum dui lorem, vulputate vitae facilisis et, consequat auctor turpis.",
"Donec eget tellus non erat gravida consectetur.",
"In lobortis velit nisi, a facilisis massa convallis eget.",
"Sed vestibulum nunc at ante dignissim euismod.",
"In ac laoreet felis.",
"Nulla feugiat finibus malesuada.",
"Integer sit amet massa sit amet elit tincidunt finibus.",
"Donec elementum ornare mi nec posuere.",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
"Proin suscipit convallis imperdiet.",
"Aliquam interdum in enim ac tristique.",
"Sed libero sapien, tempus eget fringilla in, lacinia id lacus.",
"Sed in est ac orci euismod viverra at vitae ipsum.",
"Ut viverra, dolor at interdum pulvinar, risus quam sagittis nisl, sit amet cursus felis ex nec mauris.",
"Quisque lobortis urna eget libero luctus tempor.",
"Maecenas ullamcorper est at lorem tincidunt, a imperdiet erat consectetur.",
"Nullam et sapien arcu.",
"Integer vestibulum tortor at libero rutrum consectetur.",
"Pellentesque quis aliquet elit.",
"Sed scelerisque lorem ut leo faucibus fringilla.",
"Duis finibus egestas pharetra.",
"Ut interdum nunc a ante feugiat, eu eleifend massa lobortis.",
"Maecenas molestie sapien ac elit blandit hendrerit.",
"Donec suscipit nibh ut enim ultrices, vel dictum neque cursus.",
"Vestibulum ut nisi vitae magna laoreet imperdiet.",
"Integer ut sollicitudin lorem.",
"Curabitur rutrum, sapien quis blandit molestie, ex sapien vulputate augue, non interdum lorem nulla vitae enim.",
"Fusce blandit vel massa id ornare.",
"In elit risus, blandit at mauris quis, tristique condimentum felis.",
"Nam convallis scelerisque leo, non congue lacus sagittis sed.",
"Proin et cursus augue.",
"Etiam ac magna mauris.",
"Cras pretium porta diam sit amet imperdiet.",
"Quisque blandit nunc sapien, sed rhoncus lorem tincidunt eget.",
"Vivamus pulvinar, orci sit amet hendrerit tempor, nisl turpis mattis sapien, id gravida magna mauris id risus.",
"Donec augue leo, rutrum nec dictum et, sagittis in sapien.",
"Nullam vel dapibus ex.",
"Morbi nec tortor ac libero vulputate commodo quis at quam.",
"Aenean ultrices mattis felis vel dapibus.",
"Curabitur ac tellus vitae ante vestibulum elementum sit amet a odio.",
"In hac habitasse platea dictumst.",
"Donec at vehicula arcu, sit amet sagittis nulla.",
"Nam sit amet accumsan purus.",
"In quis nulla dapibus, pulvinar eros eu, sodales urna.",
"Vestibulum sed eleifend metus.",
"Nam tortor tortor, vestibulum a quam at, commodo dapibus nisl.",
"Cras tempor eros non neque pharetra volutpat.",
"Sed nisi nisl, fringilla vitae arcu nec, imperdiet porta sapien.",
"Duis enim ante, egestas a nunc sit amet, laoreet sagittis ligula.",
"Donec ornare quis elit vel commodo.",
"Suspendisse potenti.",
"Nullam nisi urna, hendrerit ut laoreet id, placerat et metus.",
"Donec imperdiet hendrerit sem, sit amet placerat orci dignissim vel.",
"Nullam ultricies metus sapien, et venenatis ipsum vehicula non.",
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam erat volutpat.",
"Nulla fringilla scelerisque neque, nec cursus ligula aliquam eget.",
"Curabitur iaculis vestibulum metus, in dignissim lacus suscipit pellentesque.",
"Maecenas at nibh orci.",
"Nullam hendrerit felis ipsum, ut egestas elit maximus eu.",
"Aliquam erat volutpat.",
"Nulla vitae semper lacus.",
"Nulla convallis massa in aliquet commodo.",
"Integer pellentesque mattis purus, vel egestas leo congue ac.",
"Nulla facilisis ligula et justo mattis, gravida pellentesque risus aliquam.",
"Suspendisse potenti.",
"Duis sagittis mauris non accumsan tristique.",
"Suspendisse aliquam molestie massa et elementum.",
"Donec feugiat posuere orci, sit amet rutrum nibh viverra ultrices.",
"Quisque ac mauris in velit mollis dapibus id vitae diam.",
"Nullam et augue sapien.",
"In facilisis sollicitudin neque, ut mollis quam porta vel.",
"In feugiat ut augue non efficitur.",
"Nulla at hendrerit arcu, eu vehicula nibh.",
"Quisque nibh dolor, mollis non ex nec, sodales laoreet arcu.",
"Sed vulputate ligula vel massa euismod, in malesuada libero fringilla.",
"Mauris facilisis euismod nisi vel suscipit.",
"Sed auctor faucibus lorem, eget elementum purus porttitor interdum.",
"Morbi et ligula porta, tincidunt lorem quis, lobortis enim.",
"Phasellus vel rhoncus nisl.",
"Suspendisse efficitur tempor justo posuere porttitor.",
"Nulla eu ex aliquam, ultrices sapien et, imperdiet lorem.",
"Suspendisse eu malesuada diam.",
"Etiam a hendrerit orci, eu gravida metus.",
"Praesent laoreet, magna eu porta porttitor, est velit placerat ante, at dignissim lacus metus id risus.",
"Vestibulum a diam nec mauris dapibus rutrum.",
"Pellentesque nisi lectus, faucibus quis metus eu, gravida commodo nisi.",
"Cras ullamcorper dui interdum tellus cursus interdum in id erat.",
"Nunc in placerat nisl.",
"Vivamus eget euismod augue, ac euismod est.",
"Sed a lorem et ligula sagittis rhoncus at vel nunc.",
"Donec et maximus risus.",
"Maecenas quis nunc ante.",
"Nullam nisl massa, elementum vitae elit quis, maximus facilisis diam.",
"Phasellus at arcu ullamcorper, vulputate libero id, eleifend felis.",
"Nam faucibus aliquet orci nec sodales.",
"Donec fermentum commodo feugiat.",
"Morbi pharetra a mauris ac porttitor.",
"Nam rutrum, nibh in malesuada interdum, lacus augue tempus dui, id sagittis urna urna sed nisi.",
"Morbi volutpat faucibus mi, id finibus massa tempor a.",
"Aenean vitae aliquet ante, at rhoncus risus.",
"Praesent et fringilla nisl, vitae venenatis sapien.",
"Donec nec pellentesque magna.",
"Quisque eget blandit purus, vel pharetra sapien.",
"Proin varius dignissim velit egestas vehicula.",
"Phasellus imperdiet fringilla porttitor.",
"Fusce at malesuada nisl.",
"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
"Nulla sit amet felis eleifend, eleifend nisi eu, luctus mi.",
"Quisque eget felis et quam consequat elementum.",
"Nullam faucibus venenatis mi.",
"Etiam felis ipsum, aliquam id sodales quis, sagittis in mi.",
"Sed fringilla cursus turpis eget maximus.",
"Etiam et aliquet odio.",
"In pretium dolor vel ornare pellentesque.",
"Suspendisse tristique cursus metus nec auctor.",
"Fusce ultrices lacus a turpis iaculis, vitae vehicula dolor mollis.",
"Mauris ac turpis eu massa tempus rhoncus.",
"Nullam nec est nulla.",
"Donec eget bibendum dui, aliquet venenatis risus.",
"Vestibulum facilisis ac massa a tempor.",
"In sed bibendum arcu.",
"Nunc tortor lacus, luctus ut varius id, pellentesque quis risus.",
"Phasellus ut scelerisque ex.",
"Aenean porta leo at elit interdum facilisis.",
"Ut metus augue, tempor id eleifend a, finibus nec leo.",
"Nulla suscipit ornare mollis.",
"Proin auctor egestas mauris et gravida.",
"Sed id eros sed erat varius feugiat.",
"Fusce sagittis auctor tellus, non sodales leo dapibus et.",
"Curabitur at pellentesque sem.",
"Suspendisse potenti.",
"Donec eleifend nunc vitae ultricies finibus.",
"Vestibulum mauris enim, vehicula eu vulputate non, placerat in nulla.",
"Donec quis neque quis libero euismod condimentum.",
"Praesent varius accumsan dapibus.",
"Phasellus non placerat dui.",
"Ut condimentum porttitor sagittis.",
"In sit amet scelerisque ante, eget ornare arcu.",
"Phasellus eget convallis tortor, at gravida felis.",
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed dapibus facilisis lectus non dictum.",
"Ut venenatis id ipsum quis pulvinar.",
"Vivamus blandit eget arcu in maximus.",
"Aliquam mi tellus, feugiat at dolor finibus, pellentesque rutrum arcu.",
"Curabitur quis fringilla magna, porta ullamcorper nisl.",
"Donec placerat, purus non finibus bibendum, nisi turpis dictum nisl, vel lobortis neque quam non velit.",
"Sed ligula nunc, viverra ac eleifend sit amet, sodales ac eros.",
"Phasellus vel luctus est.",
"Aliquam cursus nulla nec sapien vehicula, sed aliquam ante scelerisque.",
"Vivamus placerat purus nec felis efficitur condimentum.",
"Cras posuere gravida ultrices.",
"Nunc porttitor, erat eget sagittis dictum, nisi enim luctus ligula, sit amet mollis arcu elit semper urna.",
"Donec vehicula tristique enim eget fermentum.",
"Sed imperdiet scelerisque eros.",
"Curabitur hendrerit porttitor massa.",
"Nam cursus ultrices purus.",
"Suspendisse in turpis luctus orci faucibus ullamcorper id vel odio.",
"Fusce placerat justo tortor, hendrerit ultricies orci faucibus vel.",
"Quisque gravida tortor at porttitor malesuada.",
"Donec congue quis nulla et tempus.",
"Sed tincidunt eget ipsum non auctor.",
"Suspendisse tempus diam nec massa efficitur, et faucibus erat euismod.",
"Sed elementum nisl ut hendrerit sollicitudin.",
"Suspendisse in ultricies dui, a volutpat arcu.",
"Maecenas tempus faucibus diam ultricies condimentum.",
"Vestibulum vehicula tristique consectetur.",
"Aenean imperdiet eget urna quis ultricies.",
"Donec vehicula nisl porttitor quam pulvinar, at porttitor quam laoreet.",
"Nullam at finibus arcu.",
"Cras sed faucibus dui.",
"Mauris turpis massa, mattis ut tristique quis, imperdiet sit amet justo.",
"Sed id turpis at massa mollis commodo in a nulla.",
"Aenean tempor diam in nunc posuere, vel mollis orci aliquam.",
"Vestibulum vehicula et lorem vitae tincidunt.",
"Etiam lacus nibh, luctus vel enim a, eleifend iaculis tellus.",
"Suspendisse pellentesque lorem malesuada justo aliquet blandit.",
"Cras elementum nisl non commodo interdum.",
"Praesent iaculis urna ac imperdiet pulvinar.",
"Sed a nisi quis velit volutpat molestie id sed justo.",
"Aenean eget ligula vel magna rhoncus luctus.",
"Sed ac hendrerit sapien.",
"Integer arcu nisl, bibendum non vulputate non, pretium non massa.",
"Aenean in orci quam.",
"Mauris placerat urna elit, non hendrerit sapien bibendum eu.",
"Nam quis ultricies mauris.",
"Morbi augue mi, condimentum in libero mattis, tristique venenatis nisl.",
"Aenean ut est eget nisl condimentum vestibulum.",
"Duis vulputate, dui vel cursus vestibulum, justo magna venenatis eros, semper feugiat leo augue nec tortor.",
"Etiam ultrices placerat tortor, a blandit elit tristique a.",
"Praesent sit amet pharetra magna.",
"Aliquam luctus ipsum nec auctor mattis.",
"Sed eleifend leo id arcu ultricies elementum.",
"Aenean vel massa et sem tincidunt ultricies.",
"Maecenas ac tempor orci.",
"Nullam vel dignissim ligula, in dictum mauris.",
"Curabitur at finibus orci.",
"Nunc eget purus tempus, porta justo at, condimentum arcu.",
"Aenean a eleifend leo.",
"Ut hendrerit, dui non molestie porta, sapien justo bibendum dolor, ac tincidunt sem nisi et felis.",
"Vestibulum vel diam ex.",
"Sed egestas nisl ut tortor suscipit facilisis.",
"Sed tortor augue, varius at lacinia semper, mollis eu sem.",
"Maecenas porttitor facilisis semper.",
"Vestibulum commodo elementum enim, eu ultricies sapien tristique eu.",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
"Aenean luctus dapibus finibus.",
"Pellentesque condimentum ligula eu malesuada facilisis.",
"In auctor at sapien eu dignissim.",
"Fusce suscipit quam a dolor posuere, eget facilisis lorem tristique.",
"Phasellus sed eros condimentum, mattis sapien non, pellentesque sem.",
"Sed blandit auctor tortor.",
"Nunc hendrerit semper felis sed posuere.",
"Donec condimentum mauris et nulla consequat cursus.",
"Praesent semper vulputate dui.",
"Curabitur posuere orci in nulla commodo elementum.",
"Praesent convallis rhoncus turpis, a rutrum risus venenatis sit amet.",
"Nulla eleifend ipsum mauris, sit amet tempus quam feugiat sed.",
"Donec non pulvinar ipsum.",
"Cras ultrices mollis ipsum ullamcorper ultrices.",
"Aenean sollicitudin justo ac nulla ullamcorper dignissim.",
"Aenean et leo pulvinar, tincidunt risus id, vestibulum nibh.",
"Duis aliquet, enim vitae lacinia cursus, arcu elit dignissim justo, id accumsan ex erat vitae enim.",
"Quisque vitae augue tristique, volutpat urna vel, pretium nisl.",
"Morbi auctor, tellus sed consectetur tempor, mauris sapien elementum nulla, id interdum libero neque varius eros.",
"Pellentesque tempus nisl egestas, cursus velit non, venenatis diam.",
"Nam vitae enim sed mauris auctor malesuada et eu arcu.",
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
"Nam mollis dictum leo, id tempus erat cursus non.",
"Nunc mattis vestibulum maximus.",
"Maecenas viverra nisi a ipsum tincidunt blandit.",
"Suspendisse potenti.",
"Quisque quis tincidunt sapien, eget venenatis est.",
"Sed molestie nunc et nunc lobortis ultrices.",
"Ut euismod in est ac iaculis.",
"Quisque justo neque, fringilla quis tempus quis, aliquam eu felis.",
"Sed enim nisl, pulvinar in erat non, semper efficitur massa.",
"Nam sit amet viverra enim.",
"Suspendisse blandit est enim, ut placerat leo dictum in.",
"Proin id imperdiet velit, at fermentum eros.",
"Maecenas dolor sem, dignissim sed magna sed, gravida condimentum arcu.",
"Donec neque est, pharetra nec placerat non, dignissim elementum elit.",
"Fusce sodales lorem sed justo suscipit, a posuere nunc pulvinar.",
"Donec id finibus augue, ut suscipit ligula.",
"Donec dictum lacinia magna eget volutpat.",
"Donec eget tristique tortor.",
"Vivamus egestas pulvinar lacus quis vehicula.",
"In lobortis ultrices sapien aliquet facilisis.",
"Nunc non nulla nec dolor egestas tincidunt.",
"In ultrices eros a urna ultrices, a condimentum nisl pharetra.",
"Ut vestibulum porttitor ante, vitae rhoncus leo blandit eu.",
"Aliquam pellentesque eros in rhoncus vulputate.",
"Praesent ac nunc ac ligula sodales eleifend.",
"Etiam sagittis lectus sed lorem mattis bibendum.",
"Nam at rhoncus lorem, vitae facilisis erat.",
"Vestibulum consectetur, elit auctor laoreet malesuada, sem sapien aliquam turpis, a rhoncus enim augue non tortor.",
"Ut vehicula odio eget velit condimentum, at condimentum massa placerat.",
"Sed faucibus sodales venenatis.",
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi placerat euismod pretium.",
"Nullam varius quam sed metus molestie, in ornare urna ornare.",
"Morbi lectus tellus, mattis eget eleifend ut, lacinia sed purus.",
"Aliquam mattis justo sed ex porta malesuada.",
"Quisque dictum ultrices tempor.",
"Morbi vel mi quis leo molestie maximus.",
"Curabitur odio metus, cursus non dictum id, consequat ac nulla.",
"Nullam vel eros aliquet, pretium dolor vitae, iaculis nisl.",
"Aenean aliquam nulla elit, tincidunt lobortis ipsum maximus vitae.",
"Vestibulum eu commodo elit.",
"Mauris a erat justo.",
"Etiam ut elit tristique, vulputate mauris tincidunt, varius justo.",
"Vestibulum sem augue, aliquet vel felis in, pulvinar bibendum massa.",
"Vestibulum eros diam, laoreet eu odio a, cursus tempus nisl.",
"Sed id diam tincidunt, pharetra lacus ac, tempus nisi.",
"Donec vitae leo facilisis, tincidunt tellus nec, pulvinar nisi.",
"Sed et scelerisque nisl.",
"Nam eget volutpat dui, at vulputate dui.",
"Integer a aliquet risus, eu suscipit ante.",
"Proin quis nisi et lacus scelerisque consequat.",
"Nam egestas magna sit amet purus aliquet tincidunt.",
"Curabitur vitae imperdiet augue.",
"Fusce sagittis leo quis odio fringilla semper.",
"Curabitur tincidunt semper orci sit amet mattis.",
"Pellentesque eu magna consequat, tempor enim sed, auctor ex.",
"Duis laoreet imperdiet nibh vitae mollis.",
"In mollis rhoncus leo sit amet dignissim.",
"Duis rhoncus et nibh a auctor.",
"Proin volutpat mauris vitae diam rutrum, id gravida elit elementum.",
"Etiam et feugiat lorem.",
"Fusce eget rhoncus purus.",
"Curabitur vitae lorem sit amet quam consectetur rhoncus.",
"Etiam sed venenatis elit.",
"Vivamus eu quam in sapien luctus cursus nec sit amet mauris.",
"Curabitur mollis felis nec ligula mattis congue.",
"Fusce sollicitudin nisl et semper sagittis.",
"Etiam eget leo ac tortor vehicula iaculis.",
"Aliquam erat volutpat.",
"Morbi quis nisi id magna facilisis euismod.",
"Morbi vel odio non quam varius interdum et sed eros.",
"Aliquam quis mauris in enim facilisis hendrerit in sed sem.",
"Vestibulum at justo sed massa fringilla pharetra.",
"Curabitur eget lectus nec lacus condimentum varius vitae at augue.",
"Curabitur in diam purus.",
"Aliquam erat volutpat.",
"Nullam suscipit sed augue sed placerat.",
"Duis placerat, enim in euismod consequat, justo risus mattis arcu, non blandit lectus arcu nec orci.",
"Etiam vitae rutrum nisi.",
"Nam lobortis est in tincidunt volutpat.",
"Suspendisse varius risus at diam pellentesque, eu porta nunc ultricies.",
"Maecenas posuere molestie lacus at cursus.",
"Duis erat urna, congue eget efficitur non, fermentum ac lorem.",
"Donec volutpat nulla augue, sed vehicula risus vulputate quis.",
"Curabitur purus dui, fermentum et elementum et, efficitur eget ante.",
"Phasellus vitae elit at lectus tincidunt pretium in at ex.",
"Fusce in justo interdum turpis convallis ultricies et non sem.",
"Vestibulum sagittis enim nulla, vel suscipit neque tempor eget.",
"Cras fringilla ac nibh et porttitor.",
"Cras consequat felis bibendum magna mollis, id mollis odio sagittis.",
"Mauris pretium, ligula ac consectetur ultrices, enim eros malesuada risus, porta bibendum diam nulla non tortor.",
"Donec ligula turpis, vulputate vel est ac, sodales mattis quam.",
"Nunc ac lectus et turpis interdum efficitur et non erat.",
"Cras euismod lorem quis ipsum posuere, tincidunt molestie augue pulvinar.",
"Vivamus tempus sit amet augue a lacinia.",
"Morbi ac velit rutrum, blandit nunc eu, feugiat justo.",
"Integer sollicitudin justo tellus, eu viverra dui pulvinar a.",
"Nullam condimentum tellus ipsum, non auctor diam interdum sed.",
"Pellentesque at ornare justo, vitae fermentum quam.",
"Aenean leo nulla, viverra ut turpis ac, mattis condimentum libero.",
"Aenean porta finibus finibus.",
"Nam volutpat odio et eros tempor, sed vulputate elit ultrices.",
"In gravida urna at urna cursus aliquam.",
"Donec sollicitudin elit sit amet iaculis finibus.",
"Vivamus vitae risus arcu.",
"Donec neque neque, sollicitudin vel feugiat non, imperdiet vel urna.",
"Phasellus vitae tortor vehicula, dapibus urna ac, placerat eros.",
"Nam urna mi, fermentum non blandit at, bibendum sit amet justo.",
"Aenean pellentesque accumsan pulvinar.",
"Nullam placerat laoreet quam eget pharetra.",
"Phasellus fermentum turpis facilisis, efficitur dolor vel, tincidunt sem.",
"Pellentesque vel quam fringilla ipsum laoreet malesuada.",
"Phasellus eu maximus diam, vel volutpat augue."
};
      int i, offset;

      for (offset = 0; offset < ITERS; offset++) {
            for (i = 0; find_strings[i]; i++)
            {
                  init_search(find_strings[i]);
                  here = strsearch(search_strings[i+offset]);
                  printf("\"%s\" is%s in \"%s\"", find_strings[i],
                        here ? "" : " not", search_strings[i]);
                  if (here)
                        printf(" [\"%s\"]", here);
                  putchar('\n');
            }
      }

      return 0;
}

